name: Deploy Go Program

on:
  push:
    branches:
      - prod

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21.6

      - name: Build Go program
        run: go build -o main

      - name: Use SSH key for deployment2
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Debug Loaded SSH Keys
        run: |
          ssh-add -l

      - name: Copy program to server
        run: |
          scp -o StrictHostKeyChecking=no -i deploy_key.pem ./main $SERVER_USERNAME@$SERVER_IP:/usr/local/go_chat_api
        env:
          SERVER_USERNAME: root
          SERVER_IP: 87.106.122.212
